### PR TITLE
Use union types instead of overloads whenever possible

### LINKED ISSUE #12: Bluebird.resolve
Hi,
I encountered an error when I wanted to use `.resolve` to nomalize a value  that could either be a Promise or already resolved. The compiler did not let me do that:

``` typescript
type EventualPromise<T> = T | Bluebird.Thenable<T>;

let eventualStringPromise: EventualPromise<string>;

Bluebird.resolve(eventualPromise)
  .then((resolved: string) => {
    console.log(resolved);
  });
```

This fails because `string | Bluebird.Thenable<string>` is not assignable to `string`.

Here are the related definitions:

``` typescript
// currently:
static resolve(): Bluebird<void>;
static resolve<R>(value: Bluebird.Thenable<R>): Bluebird<R>;
static resolve<R>(value: R): Bluebird<R>;

// Proposed:
static resolve(): Bluebird<void>;
static resolve<R>(value: R | Bluebird.Thenable<R>): Bluebird<R>;
```

### PR DESCRIPTION
**Pull request by louy**
Fixes #12

### CODE REVIEW

**Comment by demurgos** [comment]
It's great how it shortens most of the declarations!

**Comment by unional** [comment]
Need to be careful here. Some of them should not use union. E.g. `done()`

Use union only if it is really overload of a method with the same purpose. 

E.g. Consider how would you describe the method in JSDoc

**Comment by louy** [comment]
@Demurgos I think those declarations were written before union types existed.

@unional I don't see how `done` is any different than `then`.
http://bluebirdjs.com/docs/api/done.html

**Comment by louy** [comment]
@unional I think you meant to be careful when removing overloads as some of them have optional parameters while others don't. I fixed that. Thanks for spotting it.

**Comment by unional** [comment]
:)

I meant that when the overloads meant Tobe overloads of methods rather than params 

E.g. `done(<value or promise>)` vs `done(fulfill, reject?)`

**Comment by unional** [comment]
I apologize if my comments are short and brief. I have been answering through my phone instead of from my computer lately.

**Comment by louy** [comment]
I think this doesn't apply to `done()` (maybe an old way of doing things) but yeah I got you. No worries 😊

**Comment by unional** [comment]
🌷  Merge whenever you are comfortable to.

**Comment by demurgos** [comment]
Are there any updates ?

**Pull request merged**
