### PR TITLE
Shorthand predicate signature

### PR DESCRIPTION
**Pull request by robscotts4rb**
Altered predicate typings
Added tests for catch predicates

Addresses #22

### CODE REVIEW

**Comment by unional** [comment]
Would it be better to keep the original two and add `catch(error: { code: string, message?: string }, ...)`? (or simply `error: { code: string | any }` because message is not used)

That will provide better completion.

The build failed because of missing semicolon in the test file.

**Comment by robscotts4rb** [comment]
I did think that initially, but the predicate could be any element inside an error, so if someone has extended error classes to add an extra key, they wouldn't be able to do shorthand predicates if it was strongly typed. 

Will fix the build error now.

**Comment by unional** [comment]
Sorry, I didn't make that clear, you can create an interface to do that:

``` ts

interface SomeError {
  code: string
  [index: string]: any
}

function foo(err: SomeError) {
  return
}
foo({ code: 'abc', message: 'def' })
```

**Comment by robscotts4rb** [comment]
I think I understand what you mean, can you have a check over the last commits and see if I got it.

Thanks

**Comment by unional** [comment]
👍 
Just remember that with union type you can do this too:

``` ts
function foo(err: { code: string } & {}) { ... }
```

But interface works fine. 🌷

**Comment by blakeembrey** [comment]
Just a note, but I don't think you should specify `code` as required in the object signature - that looks like it's purely an example.

**Comment by unional** [comment]
Yes, you are right.
https://github.com/petkaantonov/bluebird/blob/master/src/catch_filter.js#L30

**Pull request merged**
