### PR TITLE
Added .getNewLibraryCopy() and .version definitions

### PR DESCRIPTION
**Pull request by lhecker**
A little late but here it is. 😊

### CODE REVIEW

**Comment by lhecker** [comment]
Ah f***. I forgot the change to the `package.json` and `typings.json` files. I **force pushed** a fix (again).

**Comment by unional** [comment]
No problem.

Next time you don't have to force push, now github support squash and merge, so it will be merged in one commit anyway. 👍

**Comment by unional** [comment]
And good job! 🌷

**Comment by lhecker** [comment]
@unional Oh right... I forgot about that. 😐 Well since it's more or less new I'm really used to manually rewriting git histories even on GitHub. Well at least then you can apply aggressive pruning of git objects, to get stale/unreferenced commits out of the object store.

**Comment by unional** [comment]
No problem. Just thinking of saving you some trouble. :)

Registry is updated so you can use it in a few minutes.

**Pull request merged**
