### PR TITLE
mapSeries added #11

### PR DESCRIPTION
**Pull request by mlegenhausen**

### CODE REVIEW

**Comment by demurgos** [comment]
Given the recent discussion (#12 and #13) about union types, I think that you could do the following replacement:

``` typescript
// promise of array with promises of value
static mapSeries<R, U>(values: Bluebird.Thenable<Bluebird.Thenable<R>[]>, iterator: (item: R, index: number, arrayLength: number) => U | Bluebird.Thenable<U>): Bluebird<U[]>;
// array with promises of value
static mapSeries<R, U>(values: Bluebird.Thenable<R>[], iterator: (item: R, index: number, arrayLength: number) => U | Bluebird.Thenable<U>): Bluebird<U[]>;
// array with values OR promise of array with values
static mapSeries<R, U>(values: R[] | Bluebird.Thenable<R[]>, iterator: (item: R, index: number, arrayLength: number) => U | Bluebird.Thenable<U>): Bluebird<U[]>;

// can be:
// Promise OR array of Promises OR values:
static mapSeries<R, U>(values: (R | Bluebird.Thenable<R>)[] | Bluebird.Thenable<(R | Bluebird.Thenable<R>)[]>, iterator: (item: R, index: number, arrayLength: number) => U | Bluebird.Thenable<U>): Bluebird<U[]>;

```

This should prevent disjunctions and allow valid usages such as:

``` ts
let array: (number | Thenable<number>)[] = [
  10,
  Bluebird.resolve(20)
];
Bluebird.mapSeries(array, ...);
```

Or

``` ts
let eventualArray: number[] | Thenable<number[]> = getEventualArray(); // returns either an array or a promise for an array
Bluebird.mapSeries(eventualArray, ...);
```

Another note: I noticed with your PR (but it's not directly related) that the usage of generics is not consistent across the whole definitions: it would be nice to have the type of the returned Promise to _always_ be the **first** generic parameter. (But this would require a new PR)

**Comment by mlegenhausen** [comment]
Fixed.

**Comment by demurgos** [comment]
Looks fine to me.

@louy, @unional: any comment ?

**Comment by louy** [comment]
I think we should have something like `type MaybeThenable<T> = T | Thenable<T>;`.

**Comment by demurgos** [comment]
Agreed, I'll do a PR next week if no one does it before.

**Pull request merged**
